trigger: none

pool:
  vmImage: 'ubuntu-18.04'


steps:

- task: PowerShell@02
  name: taskname
  displayName: check connection 
  inputs:
    azureSubscription: $(subnamee)
    scriptLocation: 'inlineScript'
    failOnStandardError: true
    targetType: 'inline'
    script: |

      ip="10.0.0.8,10.0.0.7,10.0.0.11,10.0.0.4,10.0.0.5,10.0.0.9,10.0.0.6"
      echo "ip=$(ip)" 

      for (i in $(echo $variable | sed "s/,/ /g"))
      do
         echo "$i"   
      done    

