trigger: none

pool:
  vmImage: 'ubuntu-18.04'


steps:

- task: PowerShell@02
  name: taskname
  displayName: check connection 
  inputs:
    azureSubscription: $(subnamee)
    scriptLocation: 'inlineScript'
    failOnStandardError: true
    targetType: 'inline'
    script: |

      $ip="10.0.0.8,10.0.0.7,10.0.0.11,10.0.0.4,10.0.0.5,10.0.0.9,10.0.0.6"
       echo "ip=$ip" 


        echo  "##vso[task.setvariable variable=ip]$ip"       
        $cnt = 1
        foreach ($i in $ip.Split(","))
        {
          echo "Element $cnt is $i"
             $cnt++
          }

- template: azure-pipelines.check_connection.yml
  parameters:
        param : "$ip" 
        
