trigger: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: JMETER_TERRAFORM_SETTINGS
- name: JMETER_DIRECTORY_INPUT
  value: $(System.DefaultWorkingDirectory)/jmeter
- name: JMETER_DIRECTORY_OUTPUT
  value: $(System.DefaultWorkingDirectory)/results
- name: TERRAFORM_VERSION
  value: 0.13.2



steps:

- task: PowerShell@02
  name: taskname
  displayName: check connection 
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptLocation: 'inlineScript'
    failOnStandardError: true
    targetType: 'inline'
    script: |

     Install-Module -Name Az.ContainerInstance  -force

      $Worker_name="jmete99-worker4"
      

      $SubscriptionId= "3acbc334-72a0-4b2d-b3bb-8498810f4955"

      $RG="jmete99"
      Get-AzContainerInstanceLog -ContainerGroupName jmete99-worker4 -ContainerName "jmeter" -ResourceGroupName $RG 
      
      
      echo "connection_exist=$(connection_exist)" 
      $Worker="Jmeter"
         if ("$(connection_exist)" -eq $Worker)
      {
          echo "Jmeter RUN on container instance $(Worker_name)"
      }
       else
      {
        echo "have to cancel $(Worker_name)"
      }
      
     
   


 

