trigger: none

pool:
  vmImage: 'ubuntu-18.04'


steps:

- task: PowerShell@02
  name: taskname
  displayName: check connection 
  inputs:
    azureSubscription: $(subnamee)
    scriptLocation: 'inlineScript'
    failOnStandardError: true
    targetType: 'inline'
    script: |

      ip="10.0.0.4,10.0.0.6,10.0.0.5"
      echo "ip=$(ip)" 

      for i in $(echo $variable | sed "s/,/ /g")
      do
         echo "$i"   
      done    


      $Worker="Jmeter"
         if ("$(connection_exist)" -eq $Worker)
      {
          echo "Jmeter RUN on container instance $(Worker_name)"
      }
       else
      {
        echo "have to cancel $(Worker_name)"
      }
      