trigger: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: JMETER_TERRAFORM_SETTINGS
- name: JMETER_DIRECTORY_INPUT
  value: $(System.DefaultWorkingDirectory)/jmeter
- name: JMETER_DIRECTORY_OUTPUT
  value: $(System.DefaultWorkingDirectory)/results
- name: TERRAFORM_VERSION
  value: 0.13.2



steps:
- task: AzureCLI@2
  displayName: "Get Service Principal Variables"
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=spId]$servicePrincipalId"
      echo "##vso[task.setvariable variable=spKey]$servicePrincipalKey"
      echo "##vso[task.setvariable variable=tid]$tenantId"
    addSpnToEnvironment: true

- task: PowerShell@2
  displayName: "Connect to Azure "
  inputs:
    targetType: "inline"
    script: |
    
      #    Install-Module Az -Scope CurrentUser -Force -Verbose -RequiredVersion 5.3.0
         Install-Module -Name Az.ContainerInstance  -force



        $credential = New-Object System.Management.Automation.PSCredential ("${env:SPID}", (ConvertTo-SecureString ${env:SPKEY} -AsPlainText -Force))
        Connect-AzAccount -Credential $Credential -Tenant  ${env:TID} -ServicePrincipal


      $Worker_name="jmete99-worker4"
      

      $SubscriptionId= "3acbc334-72a0-4b2d-b3bb-8498810f4955"

      $RG="jmete99"
      
      Get-AzContainerInstanceLog -ContainerGroupName jmete99-worker4 -ContainerName "jmeter" -ResourceGroupName $RG -SubscriptionId $SubscriptionId
      

        Remove-Item env:\SPKEY
        Remove-Item env:\SPID
        Remove-Item env:\TID
    pwsh: true

- task: PowerShell@02
  name: taskname
  displayName: check connection 
  inputs:
  #  azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    serviceConnectionName: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptLocation: 'inlineScript'
    failOnStandardError: true
    targetType: 'inline'
    script: |

  
  #   Install-Module -Name Az.ContainerInstance  -force

      $Worker_name="jmete99-worker4"
      

      $SubscriptionId= "3acbc334-72a0-4b2d-b3bb-8498810f4955"

      $RG="jmete99"
      $connection_detail="Get-AzContainerInstanceLog -ContainerGroupName jmete99-worker4 -ContainerName "jmeter" -ResourceGroupName $RG -SubscriptionId $SubscriptionId'
      echo "connection_detail=$connection_detail"
      
    pwsh: true
     
   


 

