trigger: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: JMETER_TERRAFORM_SETTINGS
- name: JMETER_DIRECTORY_INPUT
  value: $(System.DefaultWorkingDirectory)/jmeter
- name: JMETER_DIRECTORY_OUTPUT
  value: $(System.DefaultWorkingDirectory)/results
- name: TERRAFORM_VERSION
  value: 0.13.2

steps:


- task: Bash@3
  displayName: 'Change version of Az CLI'
  inputs:
    targetType: inline
    script: |
      sudo apt-get update
      sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
      curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
      AZ_REPO=$(lsb_release -cs)
      echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
      sudo apt-get update
      sudo apt-get install --allow-downgrades azure-cli=2.27.2-1~bionic
      

- task: AzureCLI@2
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    workingDirectory: ./terraform
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     echo "OFER"

     Worker_name="jmete99-worker1"
     RG="jmete99"
     az container logs --resource-group $RG --name $Worker_name
     log=`az container logs --resource-group jmeter1 --name jmeter1-worker_new1`
     echo "befor log parsing"
     echo $log |awk '{print $3}'
      
     check= echo ${log |awk '{print $3}'}
     echo "check="+$check
     
      connection_exist=`echo $log |awk '{print $3}')`
      echo "connection_exist"+$connection_exist
     

     connection_exist111=$(log |awk '{print $3}')
      echo "connection_exist111"+$connection_exist111
     

      new_jmeter_controller_name=$(log | grep 'Jmeter'  | awk   '{print $3}') 
            echo "new_jmeter_controller_name"+$new_jmeter_controller_name



     # If ($(connection_exist) ="Jmeter") than
     #   echo "Jmeter RUN on container instance  $Worker_name"
     # else
     #   echo "have to cancel $Worker_name"
     #fi

  displayName: 'RESULTS:  Logs check '

 

